### ISSUE TITLE
Users can't post

### ISSUE THREAD

**Issue by justoverclockl** [the-turk/flarum-nodp#1] opened 2021-07-01 17:24 UTC
After first install, i try to post with a normal user account, but i receive a console error (failed to load api/discussion/1), and i was unable to post.

https://i.ibb.co/MhXP7Dh/11.png

**Comment by the-turk** [comment] 2021-07-03 18:44
It looks like you're restricting users from editing their posts. You should allow them to edit their posts to make this extension work as designed. Having that said, extension should to check if users are actually allowed to edit their posts. So this will be fixed on the next release.

**Comment by the-turk** [comment] 2021-07-04 21:38
1.0.1 might fix this

**Comment by justoverclockl** [comment] 2021-07-05 06:33
Thanks I will try this asap

**Closed** 2021-07-12 14:21 UTC
Labels: bug, good first issue
